- name: Configurar Python
  uses: actions/setup-python@v5
  with:
    python-version: '3.11'

- name: Atualizar pip
  run: python -m pip install --upgrade pip

- name: Instalar dependencias
  run: |
    python -m pip install pytest flake8

- name: Rodar testes
  run: |
    pytest

- name: Rodar flake8
  run: |
    flake8 .